"""A1-5(Prims).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AX3PlsLwIiLah_qoaucgj7LlYYdmFgii
"""

# Function to find the vertex with the minimum key value
def min_key(vertices, keys, mst_set):
    min_key = float('inf')
    min_vertex = None
    for v in range(vertices):
        if keys[v] < min_key and not mst_set[v]:
            min_key = keys[v]
            min_vertex = v
    return min_vertex

# Function to print the minimal spanning tree
def print_mst(parent, graph):
    print("Edge   Weight")
    for i in range(1, len(parent)):
        print(parent[i], "-", i, "  ", graph[i][parent[i]])

# Prim's algorithm for minimal spanning tree
def prim_mst(graph):
    vertices = len(graph) # Number of vertices in the graph

    # Initialize key values and MST set
    keys = [float('inf')] * vertices
    parent = [None] * vertices
    mst_set = [False] * vertices

    # Starting vertex
    keys[0] = 0
    parent[0] = -1

    for _ in range(vertices - 1):
        # Choose the vertex with the minimum key value
        u = min_key(vertices, keys, mst_set)

        # Add the chosen vertex to the MST set
        mst_set[u] = True

        # Update the key values of adjacent vertices
        for v in range(vertices):
            if graph[u][v] > 0 and not mst_set[v] and graph[u][v] < keys[v]:
                keys[v] = graph[u][v]
                parent[v] = u

    # Print the minimal spanning tree
    print_mst(parent, graph)

# Take input from the user for the graph
vertices = int(input("Enter the number of vertices: "))
graph = []
for _ in range(vertices):
    row = list(map(int, input("Enter the weights for the vertices separated by spaces: ").split()))
    graph.append(row)

# Find the minimal spanning tree using Prim's algorithm
prim_mst(graph)